name: Package Registry Cleanup

on:
  push:
    branches: ["main"]

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: ghcr.io cleanup action
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          # dry-run: true
          older-than: 2 week
